# Form implementation generated from reading ui file 'ui_Winnie.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(695, 512)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: #22222e")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 701, 61))
        self.frame.setStyleSheet("background-color: #fb5b5d")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(220, 20, 241, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.input_text = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_text.setGeometry(QtCore.QRect(90, 120, 491, 111))
        self.input_text.setStyleSheet("background-color: white")
        self.input_text.setText("")
        self.input_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.input_text.setObjectName("input_text")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 90, 381, 20))
        self.label_2.setStyleSheet("color: white")
        self.label_2.setObjectName("label_2")
        self.result = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.result.setGeometry(QtCore.QRect(90, 360, 491, 41))
        self.result.setStyleSheet("background-color: white")
        self.result.setObjectName("result")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 330, 251, 16))
        self.label_3.setStyleSheet("color: white")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 270, 100, 32))
        self.pushButton.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: grey;\n"
"}\n"
"\n"
"QPushButton:pressed  {\n"
"color: grey;\n"
"background-color: black;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 695, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Пум пурум Парам пампам"))
        self.label_2.setText(_translate("MainWindow", "Введите стихотворение Винни-Пуха:"))
        self.label_3.setText(_translate("MainWindow", "Оценка ритма:"))
        self.pushButton.setText(_translate("MainWindow", "Оценить ритм"))
